version: '3'

services:
  mysql:
    image: mysql:5.6
    container_name: modulo.mysql
    environment:
      MYSQL_DATABASE: magento
      MYSQL_USER: modulo
      MYSQL_PASSWORD: rede
      MYSQL_ROOT_PASSWORD: rede
    networks:
    - modulo-rede
    volumes:
    - .mysql:/var/lib/mysql:z

  magento2:
    image: magento:2.3
    build: .
    container_name: modulo.magento-2.3
    ports:
    - "80:80"
    links:
    - mysql
    depends_on:
    - mysql
    networks:
    - modulo-rede

networks:
  modulo-rede:
    driver: bridge
